FROM golang:1.15.8-alpine AS build

# Add required packages
RUN apk add --update git curl bash

# Install revel framework
RUN go get -u github.com/revel/revel
RUN go get -u github.com/revel/cmd/revel

WORKDIR /go-revel-blog
ADD . .
ENV CGO_ENABLED 0
RUN go mod download

# Run revel app
ENTRYPOINT revel run
